### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by gamble27** [kz6fittycent/corny-jokes#1]
Hello there) 
I am not actually sure if this is a bug in your app, but there are some UTF-8 characters non-convertible to ASCII:

```
~$ cornyjokes
Traceback (most recent call last):
  File "/snap/cornyjokes/79/bin/cornyjokes", line 5, in <module>
    libcornyjokes.main()
  File "/snap/cornyjokes/79/lib/python3.5/site-packages/libcornyjokes/__init__.py", line 31, in main
    print(build_bubble(random.choice(quotes_file.readlines())))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 172: ordinal not in range(128)
```

**Comment by kz6fittycent** [comment]
I believe I have it fixed. Do you mind trying the "edge" version?

`sudo snap install cornyjokes --edge`

Thanks for showing me this.

**Comment by kz6fittycent** [comment]
I've released to the `stable` channel. Closing this out as I've not seen any issues.
